# Generated by Django 4.2.1 on 2023-05-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
