# Generated by Django 4.2.1 on 2023-05-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_template_comments_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
