# Generated by Django 4.2.1 on 2023-05-12 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='template',
        ),
    ]
