# Generated by Django 4.2.1 on 2023-05-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comment_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_number',
            field=models.IntegerField(default=0),
        ),
    ]
