# Generated by Django 4.2.1 on 2023-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_template_template_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='last_frame_url',
            field=models.ImageField(blank=True, upload_to='last_frames'),
        ),
    ]
